# Generated by Django 2.1.3 on 2018-11-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_quanity',
            new_name='product_quantity',
        ),
    ]
